### ISSUE TITLE
New Two.js Update

### ISSUE THREAD

**Issue by llevasseur** [juliendargelos/twojs-multiline-text#1]
Hi there,

Thank you for developing this tool for Two.js! 
I was wondering if you could update your library for the new Two.js update?

Thanks

Edit [May 16, 2022]: 
I've resorted to including Two.js in my HTML rather than requiring or importing it. Then, I can comment out the require statement for Two.js in node_modules/twojs-multiline-text/index.js, and it works again. However, this is annoying to do each time I have to reinstall modules on different machines while working.

I believe there is an issue with the object that is returned when requiring Two.js ^v0.8.7

**Comment by juliendargelos** [comment]
Hi, sorry for the late reply !

I will release an update as soon as possible, thanks for raising this issue

**Comment by juliendargelos** [comment]
It should now work with two.js 0.8 after updating this package to version 1.0.0.

**Comment by llevasseur** [comment]
Thank you!
