### ISSUE TITLE
[Bug] Vertical alignment

### ISSUE THREAD

**Issue by joex92** [juliendargelos/twojs-multiline-text#3]
add a `.verticalAlignment` parameter so the text can be either centered on top, center or bottom of the position point.
or improve the `.alignment` parameter to accept a 2 size String Array for both alignments: `[Horizontal, Vertical]`

**Comment by joex92** [comment]
I was using `.center()` to center everything to the position point, but when I change the text value, it decenters...

**Comment by joex92** [comment]
ok, seems like `.baseline` is the vertical alignment but it's not working...
seems to only align it to the first line and not the whole text...

**Comment by juliendargelos** [comment]
Hi @joex92, I will be looking into this soon, thanks for opening the issue

**Comment by joex92** [comment]
nice thanks... I believe instead of a new parameter better fix how `.baseline` works on a multiline text... It's working like in the original `Two.Text` object, which aligns vertically on 1 line (because `Two.Text` is only 1 line of text), but in this case it should align vertically across all the lines of text... 👍

**Comment by juliendargelos** [comment]
Yes indeed, after looking deeper at your issue, it looks like it's not about a bug with how `baseline` works but more about requesting a new feature that would set a vertical anchor point to the whole text. « Baseline » [does refer to a single line alignment](https://en.wikipedia.org/wiki/Baseline_(typography)) so changing its behavior as you propose would be semantically confusing.


I believe this is not in the scope of this library and should be done using the methods already provided by Two.js. For instance, to vertically and horizontally center a whole text on point `(200; 200)`:


```javascript
const position = new Two.Vector(200, 200)
const text = new MultilineText('Hello\nWorld', 0, 0, { alignment: 'center' })

const rect = text.getBoundingClientRect()

text.translation.x = position.x - rect.width / 2
text.translation.y = position.y - rect.height / 2
```

**Comment by joex92** [comment]
it shouldn't be confusing, because this is a `MultilineText` object, so it should make sense that `.baseline` should anchor vertically across all the lines...
the original `Text` object shouldn't fix this, because the `Text` object is not intended for multiple lines, so it will only work for 1 line and it wouldn't need a fix for something that is not intended for, otherwise `MultilineText` wouldn't even exist...
It actually is more confusing to do extra steps just to have an anchor center vertically... 🤷🏼‍♂️

**Comment by juliendargelos** [comment]
I'm sorry, I truely insist on my previous point, please read the linked wikipedia page for more informations about the strict meaning of "Baseline".

In twojs you would have to do those "extra steps" to center basically any shape. I'm trying to keep this library consistent with the API it lives in. Feel free to fork and edit it though.
